import { PrismaClient } from "@prisma/client";
import { seedShipping } from "./shipping-seed";
import { ensureDefaultCatalogs } from "../src/lib/catalogs";

const prisma = new PrismaClient();

const I = (name: string) => `/images/${name}`;

const C = (items: { nameFr: string; nameAr: string; image: string }[]) => JSON.stringify(items);

async function main() {
  await prisma.review.deleteMany();
  await prisma.order.deleteMany();
  await prisma.product.deleteMany();
  await prisma.galleryImage.deleteMany();

  await prisma.siteSettings.upsert({
    where: { id: 1 },
    update: {
      instagramUrl: "",
      facebookUrl: "",
      tiktokUrl: "",
      whatsapp: "",
    },
    create: {
      instagramUrl: "",
      email: "contact@zellaluxe.dz",
      addressFr: "Algérie",
      addressAr: "الجزائر",
    },
  });

  const products = [
    {
      slug: "valise-dior-oblique-navy",
      nameFr: "Valise Dior Oblique Navy",
      nameAr: "حقيبة سفر Dior Oblique",
      descriptionFr: "Valise cabine haute gamme motif Oblique navy & crème. Bande Christian Dior Paris, roulettes 360°.",
      descriptionAr: "حقيبة سفر فاخرة بنمط Oblique أزرق وكريمي. عجلات دوارة.",
      price: 48500,
      category: "VALISES",
      images: JSON.stringify([I("valise-dior-oblique-navy.jpg")]),
      sizes: JSON.stringify(["Cabine"]),
      stock: 4,
      featured: true,
    },
    {
      slug: "valise-lv-monogram-brun",
      nameFr: "Valise LV Monogram Brun",
      nameAr: "حقيبة سفر LV Monogram",
      descriptionFr: "Valise Louis Vuitton monogram classique brun & beige. Poignée télescopique, roulettes spinner.",
      descriptionAr: "حقيبة سفر Louis Vuitton Monogram كلاسيكية.",
      price: 52000,
      category: "VALISES",
      images: JSON.stringify([I("valise-lv-monogram-brun.jpg")]),
      sizes: JSON.stringify(["Cabine", "Moyenne"]),
      stock: 3,
      featured: true,
      onPromo: true,
      promoPrice: 44900,
    },
    {
      slug: "valise-lv-damier-gris",
      nameFr: "Valise LV Damier Graphite",
      nameAr: "حقيبة سفر LV Damier",
      descriptionFr: "Valise Damier graphite gris & noir. Élégance voyage, finitions premium.",
      descriptionAr: "حقيبة سفر Damier رمادية وسوداء.",
      price: 46500,
      category: "VALISES",
      images: JSON.stringify([I("valise-lv-damier-gris.jpg")]),
      sizes: JSON.stringify(["Cabine"]),
      stock: 5,
      featured: false,
    },
    {
      slug: "talons-platform-brodes-trio",
      nameFr: "Talons Platform Brodés — Trio",
      nameAr: "كعب platform مطرز — ثلاثي",
      descriptionFr: "Talons platform broderie florale. Bordeaux, nude et noir. Collection Zella Luxe.",
      descriptionAr: "كعب platform مع تطريز زهري. بوردو، nude وأسود.",
      price: 10500,
      category: "TALONS",
      images: JSON.stringify([I("talons-platform-brodes-trio.jpg")]),
      colors: C([
        { nameFr: "Bordeaux", nameAr: "بوردو", image: I("talons-platform-brodes-trio.jpg") },
        { nameFr: "Nude", nameAr: "nude", image: I("talons-platform-brodes-trio.jpg") },
        { nameFr: "Noir", nameAr: "أسود", image: I("talons-platform-brodes-trio.jpg") },
      ]),
      sizes: JSON.stringify(["36", "37", "38", "39", "40"]),
      stock: 12,
      featured: true,
    },
    {
      slug: "talons-slingback-paillettes",
      nameFr: "Talons Slingback Paillettes",
      nameAr: "كعب slingback لامع",
      descriptionFr: "Escarpins slingback platform or, blanc et noir avec nœud strass.",
      descriptionAr: "حذاء slingback platform ذهبي وأبيض وأسود مع فيونكة.",
      price: 11800,
      category: "TALONS",
      images: JSON.stringify([I("talons-slingback-paillettes.jpg")]),
      colors: C([
        { nameFr: "Or", nameAr: "ذهبي", image: I("talons-slingback-paillettes.jpg") },
        { nameFr: "Blanc", nameAr: "أبيض", image: I("talons-slingback-paillettes.jpg") },
        { nameFr: "Noir", nameAr: "أسود", image: I("talons-slingback-paillettes.jpg") },
      ]),
      sizes: JSON.stringify(["36", "37", "38", "39"]),
      stock: 10,
      featured: true,
      onPromo: true,
      promoPrice: 9900,
    },
    {
      slug: "talons-slingback-cristal-trio",
      nameFr: "Talons Slingback Cristal",
      nameAr: "كعب slingback كريstal",
      descriptionFr: "Talons slingback sangles cristal. Or, argent et blanc.",
      descriptionAr: "كعب slingback بأحزمة كريstal. ذهبي وفضي وأبيض.",
      price: 12200,
      category: "TALONS",
      images: JSON.stringify([I("talons-slingback-cristal-trio.jpg")]),
      colors: C([
        { nameFr: "Or", nameAr: "ذهبي", image: I("talons-slingback-cristal-trio.jpg") },
        { nameFr: "Argent", nameAr: "فضي", image: I("talons-slingback-cristal-trio.jpg") },
        { nameFr: "Blanc", nameAr: "أبيض", image: I("talons-slingback-cristal-trio.jpg") },
      ]),
      sizes: JSON.stringify(["36", "37", "38", "39"]),
      stock: 8,
      featured: true,
    },
    {
      slug: "talons-platform-perles-trio",
      nameFr: "Talons Platform Perles",
      nameAr: "كعب platform لؤلؤ",
      descriptionFr: "Talons platform brodés perles et strass. Blanc, argent et or.",
      descriptionAr: "كعب platform مطرز باللؤlؤ. أبيض وفضي وذهبي.",
      price: 12500,
      category: "TALONS",
      images: JSON.stringify([I("talons-platform-perles-trio.jpg")]),
      colors: C([
        { nameFr: "Blanc", nameAr: "أبيض", image: I("talons-platform-perles-trio.jpg") },
        { nameFr: "Argent", nameAr: "فضي", image: I("talons-platform-perles-trio.jpg") },
        { nameFr: "Or", nameAr: "ذهبي", image: I("talons-platform-perles-trio.jpg") },
      ]),
      sizes: JSON.stringify(["36", "37", "38", "39"]),
      stock: 7,
      featured: false,
    },
    {
      slug: "set-broderie-blanc",
      nameFr: "Set Broderie Blanc — Sac & Talon",
      nameAr: "طقم تطريز أبيض — حقيبة وحذاء",
      descriptionFr: "Ensemble sac carré et escarpin broderie florale blanche avec perles.",
      descriptionAr: "طقم حقيبة وحذاء أبيض مطرز بالزهور واللؤlؤ.",
      price: 16800,
      category: "SACS",
      images: JSON.stringify([I("set-broderie-blanc.jpg")]),
      sizes: JSON.stringify(["36", "37", "38", "Unique"]),
      stock: 4,
      featured: true,
    },
    {
      slug: "set-dior-cloute-noir",
      nameFr: "Set Dior Clouté Noir",
      nameAr: "طقم Dior مStudded أسود",
      descriptionFr: "Sac carré clouté noir et slingback assorti. Finitions luxe.",
      descriptionAr: "حقيبة وحذاء أسود studded فاخر.",
      price: 18500,
      category: "SACS",
      images: JSON.stringify([I("set-dior-cloute-noir.jpg")]),
      sizes: JSON.stringify(["37", "38", "39", "Unique"]),
      stock: 3,
      featured: true,
    },
    {
      slug: "sac-lv-capucines",
      nameFr: "Sac LV Capucines",
      nameAr: "حقيبة LV Capucines",
      descriptionFr: "Sac Capucines cuir grainé, logo LV doré, chaîne amovible. Disponible en crème et tan.",
      descriptionAr: "حقيبة Capucines جلد فاخر. متوفرة بالكريمي والبيج.",
      price: 24500,
      category: "SACS",
      images: JSON.stringify([I("sac-lv-capucines-cream.jpg"), I("sac-lv-capucines-tan.jpg")]),
      colors: C([
        { nameFr: "Crème", nameAr: "كريمي", image: I("sac-lv-capucines-cream.jpg") },
        { nameFr: "Tan", nameAr: "بيج", image: I("sac-lv-capucines-tan.jpg") },
      ]),
      sizes: JSON.stringify(["Unique"]),
      stock: 4,
      featured: true,
    },
    {
      slug: "slingback-dg-trio",
      nameFr: "Slingback DG — Trio",
      nameAr: "سlingback DG — ثلاثي",
      descriptionFr: "Escarpins slingback avec logo DG doré. Noir, nude et blanc.",
      descriptionAr: "حذاء slingback مع شعار DG ذهبي.",
      price: 8800,
      category: "TALONS",
      images: JSON.stringify([I("slingback-trio.jpg")]),
      colors: C([
        { nameFr: "Noir", nameAr: "أسود", image: I("slingback-trio.jpg") },
        { nameFr: "Nude", nameAr: "nude", image: I("slingback-trio.jpg") },
        { nameFr: "Blanc", nameAr: "أبيض", image: I("slingback-trio.jpg") },
      ]),
      sizes: JSON.stringify(["36", "37", "38", "39"]),
      stock: 12,
      featured: false,
      onPromo: true,
      promoPrice: 7200,
    },
    {
      slug: "sandales-baroque-or",
      nameFr: "Sandales Talon Baroque Or",
      nameAr: "صندل كعب باروك ذهبي",
      descriptionFr: "Talon sculptural baroque en or. Sandales noir et nude.",
      descriptionAr: "كعب باروك ذهبي منحوت. أسود وnude.",
      price: 11500,
      category: "TALONS",
      images: JSON.stringify([I("baroque-sandal.jpg")]),
      colors: C([
        { nameFr: "Noir", nameAr: "أسود", image: I("baroque-sandal.jpg") },
        { nameFr: "Nude", nameAr: "nude", image: I("baroque-sandal.jpg") },
      ]),
      sizes: JSON.stringify(["36", "37", "38", "39"]),
      stock: 8,
      featured: false,
      onPromo: true,
      promoPrice: 9500,
    },
    {
      slug: "bottes-noires-boucle",
      nameFr: "Bottes Noires Boucle Or",
      nameAr: "بوت أسود مبkl",
      descriptionFr: "Bottes montantes en cuir noir avec boucle dorée. Style avant-gardiste.",
      descriptionAr: "بوت جلد أسود مع buckle ذهبي.",
      price: 12000,
      category: "CHAUSSURES",
      images: JSON.stringify([I("boots-black.jpg")]),
      sizes: JSON.stringify(["36", "37", "38", "39", "40"]),
      stock: 6,
      featured: false,
    },
    {
      slug: "sacs-cristal-noir",
      nameFr: "Sacs Cristal Noir & Chaîne Or",
      nameAr: "حقائب كريstal أسود",
      descriptionFr: "Sacs pailletés cristal noir avec chaîne dorée et logo LV.",
      descriptionAr: "حقائب كريstal سوداء مع سلسلة ذهبية.",
      price: 15000,
      category: "SACS",
      images: JSON.stringify([I("bags-crystal.jpg")]),
      sizes: JSON.stringify(["Unique"]),
      stock: 5,
      featured: false,
      onPromo: true,
      promoPrice: 12500,
    },
    {
      slug: "set-dg-vernis-noir",
      nameFr: "Set DG Vernis Noir",
      nameAr: "طقم DG أسود لامع",
      descriptionFr: "Sac et sandale vernis noir avec logo DG baroque doré.",
      descriptionAr: "حقيبة وصندل DG أسود لامع.",
      price: 13500,
      category: "POCHETTES",
      images: JSON.stringify([I("patent-dg-set.jpg")]),
      sizes: JSON.stringify(["36", "Unique"]),
      stock: 5,
      featured: false,
    },
    {
      slug: "valise-lv-monogram-rouge",
      nameFr: "Valise LV Monogram Rouge",
      nameAr: "حقيبة LV Monogram حمراء",
      descriptionFr: "Valise cabine Louis Vuitton monogram avec protections rouges. Poignée télescopique, roulettes 360°.",
      descriptionAr: "حقيبة سفر LV Monogram مع زوايا حمراء.",
      price: 49500,
      category: "VALISES",
      images: JSON.stringify([I("valise-lv-monogram-rouge.jpg")]),
      sizes: JSON.stringify(["Cabine"]),
      stock: 3,
      featured: true,
    },
    {
      slug: "valise-lv-damier-graphite-box",
      nameFr: "Valise LV Damier Graphite — Boîte",
      nameAr: "حقيبة LV Damier Graphite",
      descriptionFr: "Valise Damier graphite avec boîte orange LV. Set complet avec certificats.",
      descriptionAr: "حقيبة Damier Graphite مع علبة LV.",
      price: 51000,
      category: "VALISES",
      images: JSON.stringify([I("valise-lv-damier-graphite-box.jpg")]),
      sizes: JSON.stringify(["Cabine"]),
      stock: 2,
      featured: false,
    },
    {
      slug: "botte-guêtre-boucle",
      nameFr: "Botte Guêtre Boucle Or",
      nameAr: "بوت Guêtre مشبك ذهبي",
      descriptionFr: "Bottes guêtre cuir lisse, bout pointu, fermoir doré signature. Disponible en bordeaux et marron.",
      descriptionAr: "بوت guêtre جلد مع buckle ذهبي. بوردو وكستنائي.",
      price: 18500,
      category: "CHAUSSURES",
      images: JSON.stringify([I("botte-guêtre-bordeaux.jpg"), I("botte-guêtre-marron.jpg")]),
      colors: C([
        { nameFr: "Bordeaux", nameAr: "بوردو", image: I("botte-guêtre-bordeaux.jpg") },
        { nameFr: "Marron", nameAr: "كستنائي", image: I("botte-guêtre-marron.jpg") },
      ]),
      sizes: JSON.stringify(["36", "37", "38", "39", "40"]),
      stock: 8,
      featured: true,
    },
    {
      slug: "set-orange-rayure",
      nameFr: "Set Orange Rayé — Sac & Mules",
      nameAr: "طقم برتقالي مخطط",
      descriptionFr: "Sac cabas rayures orange & crème avec mules plateforme tressées assorties.",
      descriptionAr: "حقيبة مخططة برتقالية مع mules مطابقة.",
      price: 14200,
      category: "SACS",
      images: JSON.stringify([I("set-orange-rayure.jpg")]),
      sizes: JSON.stringify(["36", "37", "38", "Unique"]),
      stock: 5,
      featured: true,
    },
    {
      slug: "set-julia-canvas-beige",
      nameFr: "Set Julia Canvas Beige",
      nameAr: "طقم Julia كانڤاس بيج",
      descriptionFr: "Sac carré canvas beige et cuir cognac avec sandales à boucles dorées.",
      descriptionAr: "حقيبة كانڤاس بيج مع صندل buckle ذهبي.",
      price: 15800,
      category: "SACS",
      images: JSON.stringify([I("set-julia-canvas-beige.jpg")]),
      sizes: JSON.stringify(["36", "37", "38", "Unique"]),
      stock: 4,
      featured: false,
    },
    {
      slug: "set-strass-multicolore",
      nameFr: "Set Strass Multicolore — Sac & Slingback",
      nameAr: "طقم strass ملون",
      descriptionFr: "Sac poignée strass multicolore et slingback cristal avec studs dorés.",
      descriptionAr: "حقيبة strass ملونة مع slingback كريstal.",
      price: 19500,
      category: "SACS",
      images: JSON.stringify([I("set-strass-multicolore.jpg")]),
      sizes: JSON.stringify(["36", "37", "38", "39", "Unique"]),
      stock: 3,
      featured: true,
    },
    {
      slug: "pochette-strass-bambou",
      nameFr: "Pochette Strass Poignée Bambou",
      nameAr: "POCHETTE strass بامبو",
      descriptionFr: "Pochettes soirée entièrement strass, poignée bambou dorée. Multicolore, or, argent ou noir & or.",
      descriptionAr: "POCHETTE مسائية strass مع مقبض بامبو.",
      price: 9800,
      category: "POCHETTES",
      images: JSON.stringify([I("pochette-strass-multicolore.jpg")]),
      colors: C([
        { nameFr: "Multicolore", nameAr: "متعدد", image: I("pochette-strass-multicolore.jpg") },
        { nameFr: "Or", nameAr: "ذهبي", image: I("pochette-or-strass.jpg") },
        { nameFr: "Argent", nameAr: "فضي", image: I("pochette-argent-strass.jpg") },
        { nameFr: "Noir & Or", nameAr: "أسود وذهبي", image: I("pochette-noir-or-strass.jpg") },
      ]),
      sizes: JSON.stringify(["Unique"]),
      stock: 10,
      featured: true,
    },
    {
      slug: "talons-platform-cristal",
      nameFr: "Talons Platform Cristal",
      nameAr: "كعب platform كريstal",
      descriptionFr: "Talons platform bout strass, lanière cheville. Or, argent et rose gold.",
      descriptionAr: "كعب platform مع strass. ذهبي وفضي وrose gold.",
      price: 13200,
      category: "TALONS",
      images: JSON.stringify([I("talons-platform-cristal-or.jpg")]),
      colors: C([
        { nameFr: "Or", nameAr: "ذهبي", image: I("talons-platform-cristal-or.jpg") },
        { nameFr: "Argent", nameAr: "فضي", image: I("talons-platform-cristal-or.jpg") },
        { nameFr: "Rose Gold", nameAr: "rose gold", image: I("talons-platform-cristal-or.jpg") },
      ]),
      sizes: JSON.stringify(["36", "37", "38", "39"]),
      stock: 9,
      featured: true,
      onPromo: true,
      promoPrice: 10900,
    },
    {
      slug: "mules-strass-plateforme",
      nameFr: "Mules Strass Plateforme",
      nameAr: "mules strass platform",
      descriptionFr: "Mules talon strass, bout carré, lanière ajourée. Argent, noir et or.",
      descriptionAr: "mules strass بكعب platform. فضي وأسود وذهبي.",
      price: 11200,
      category: "TALONS",
      images: JSON.stringify([I("mule-strass-trio.jpg")]),
      colors: C([
        { nameFr: "Argent", nameAr: "فضي", image: I("mule-strass-argent.jpg") },
        { nameFr: "Noir", nameAr: "أسود", image: I("mule-strass-noir.jpg") },
        { nameFr: "Or", nameAr: "ذهبي", image: I("mule-strass-or.jpg") },
      ]),
      sizes: JSON.stringify(["36", "37", "38", "39"]),
      stock: 12,
      featured: true,
    },
    {
      slug: "escarpin-strass-cristal",
      nameFr: "Escarpin Strass Cristal",
      nameAr: "escarpin strass كريstal",
      descriptionFr: "Escarpins slingback cristaux, bout pointu. Or, argent et blanc nacré.",
      descriptionAr: "escarpin strass كريstal. ذهبي وفضي وأبيض.",
      price: 12800,
      category: "TALONS",
      images: JSON.stringify([I("escarpin-strass-trio.jpg")]),
      colors: C([
        { nameFr: "Or", nameAr: "ذهبي", image: I("escarpin-strass-or.jpg") },
        { nameFr: "Argent", nameAr: "فضي", image: I("escarpin-strass-argent.jpg") },
        { nameFr: "Blanc", nameAr: "أبيض", image: I("escarpin-strass-blanc.jpg") },
      ]),
      sizes: JSON.stringify(["36", "37", "38", "39", "40"]),
      stock: 15,
      featured: true,
      onPromo: true,
      promoPrice: 10500,
    },
  ];

  for (const product of products) {
    await prisma.product.create({ data: product });
  }

  const slingback = await prisma.product.findUnique({ where: { slug: "talons-slingback-paillettes" } });
  const valise = await prisma.product.findUnique({ where: { slug: "valise-dior-oblique-navy" } });

  await prisma.review.createMany({
    data: [
      {
        customerName: "Amira B.",
        message: "Talons magnifiques, qualité au top ! Livraison rapide à Alger. Je recommande Zella Luxe.",
        rating: 5,
        status: "APPROVED",
        productId: slingback?.id,
        photos: "[]",
      },
      {
        customerName: "Sarah K.",
        message: "Ma valise Dior est magnifique, qualité premium ! Livraison soignée.",
        rating: 5,
        status: "APPROVED",
        productId: valise?.id,
        photos: "[]",
      },
      {
        customerName: "Nadia M.",
        message: "Super service, je reviendrai pour la prochaine collection.",
        rating: 4,
        status: "PENDING",
        photos: "[]",
      },
    ],
  });

  const galleryImages = [
    { url: I("valise-lv-monogram-rouge.jpg"), captionFr: "Valise LV Monogram Rouge", captionAr: "حقيبة LV حمراء", sortOrder: 1 },
    { url: I("valise-lv-damier-graphite-box.jpg"), captionFr: "Valise Damier Graphite", captionAr: "حقيبة Damier", sortOrder: 2 },
    { url: I("valise-dior-oblique-navy.jpg"), captionFr: "Valises Haute Gamme", captionAr: "حقائب سفر فاخرة", sortOrder: 3 },
    { url: I("set-strass-multicolore.jpg"), captionFr: "Set Strass Multicolore", captionAr: "طقم strass", sortOrder: 4 },
    { url: I("escarpin-strass-trio.jpg"), captionFr: "Escarpins Strass Cristal", captionAr: "escarpin strass", sortOrder: 5 },
    { url: I("mule-strass-trio.jpg"), captionFr: "Mules Strass", captionAr: "mules strass", sortOrder: 6 },
    { url: I("pochette-or-strass.jpg"), captionFr: "Pochette Or Strass", captionAr: "POCHETTE ذهبية", sortOrder: 7 },
    { url: I("botte-guêtre-bordeaux.jpg"), captionFr: "Botte Guêtre Bordeaux", captionAr: "بوت guêtre", sortOrder: 8 },
    { url: I("set-orange-rayure.jpg"), captionFr: "Set Orange Rayé", captionAr: "طقم برتقالي", sortOrder: 9 },
    { url: I("set-julia-canvas-beige.jpg"), captionFr: "Set Julia Canvas", captionAr: "طقم Julia", sortOrder: 10 },
    { url: I("talons-platform-cristal-or.jpg"), captionFr: "Collection Platform Cristal", captionAr: "platform كريstal", sortOrder: 11 },
    { url: I("talons-platform-clutch-set.jpg"), captionFr: "Platform & Pochette", captionAr: "platform وPOCHETTE", sortOrder: 12 },
    { url: I("talons-slingback-clutch-noir.jpg"), captionFr: "Slingback & Clutch Noir", captionAr: "slingback أسود", sortOrder: 13 },
    { url: I("set-dior-cloute-noir.jpg"), captionFr: "Set Dior Noir", captionAr: "طقم Dior أسود", sortOrder: 14 },
    { url: I("set-broderie-blanc.jpg"), captionFr: "Set Broderie Blanc", captionAr: "طقم تطريز أبيض", sortOrder: 15 },
    { url: I("sac-lv-capucines-cream.jpg"), captionFr: "Sac Capucines", captionAr: "حقيبة Capucines", sortOrder: 16 },
    { url: I("talons-platform-brodes-trio.jpg"), captionFr: "Talons Platform Brodés", captionAr: "كعب platform مطرز", sortOrder: 17 },
    { url: I("talons-slingback-cristal-trio.jpg"), captionFr: "Slingback Cristal", captionAr: "slingback كريstal", sortOrder: 18 },
    { url: I("bags-crystal.jpg"), captionFr: "Sacs Cristal", captionAr: "حقائب كريstal", sortOrder: 19 },
    { url: I("baroque-sandal.jpg"), captionFr: "Talon Baroque", captionAr: "كعب باروك", sortOrder: 20 },
  ];

  for (const img of galleryImages) {
    await prisma.galleryImage.create({ data: img });
  }

  await seedShipping(prisma);
  await ensureDefaultCatalogs();

  console.log("✅ Seed with real Zella Luxe photos!");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
